export const GET_OF_CHAIN_VOTER = "GET_OF_CHAIN_VOTER";
export const GET_NOMINATORS = "GET_NOMINATORS";
export const GET_NOMINATORS_LENGTH = "GET_NOMINATORS";
export const GET_WALLET_ADDRESS = "GET_WALLET_ADDRESS";
export const GET_CYCLE_TIME = "GET_CYCLE_TIME";
export const GET_PROFILE_DATA ="GET_PROFILE_DATA";
export const IS_VOTED = "IS_VOTED";
